spring.application.name=mini

server.port=8088

# --- MySQL Database Configuration ---
spring.datasource.url=jdbc:mysql://localhost:3306/otp_demo?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Nikhil@1209
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
# --- Hibernate / JPA Settings ---

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# --- JSP view resolver ---
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
# Vonage API credentials
vonage.api.key=5416fe71
vonage.api.secret=pG5xG3dnUC3VKvOU
vonage.sms.from=Digital_miniclinic
vonage.from.number=+917406890765
# VideoSDK API
